/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './app.css.shim';
import * as import1 from '@angular/core/src/linker/debug_context';
import * as import2 from '@angular/core/src/linker/template_ref';
import * as import3 from '@angular/common/src/directives/ng_for';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/view';
import * as import6 from './app';
import * as import7 from '@angular/core/src/linker/element';
import * as import8 from '@angular/core/src/linker/view_utils';
import * as import9 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/linker/view_type';
import * as import11 from '@angular/core/src/change_detection/change_detection';
import * as import12 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from './weather-card';
import * as import15 from './weather-card.ngfactory';
import * as import16 from '@angular/core/src/linker/component_factory';
const styles_WeatherApp:any[] = [import0.styles];
const nodeDebugInfos_WeatherApp0:import1.StaticNodeDebugInfo[] = [
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([
    import2.TemplateRef,
    import3.NgFor
  ]
  ,null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{})
]
;
var renderType_WeatherApp:import4.RenderComponentType = null;
class _View_WeatherApp0 extends import5.DebugAppView<import6.WeatherApp> {
  _el_0: any;
  _text_1: any;
  _el_2: any;
  _text_3: any;
  _text_4: any;
  _el_5: any;
  _text_6: any;
  _el_7: any;
  _text_8: any;
  _text_9: any;
  _el_10: any;
  _text_11: any;
  _anchor_12: any;
  private _appEl_12:import7.AppElement;
  _TemplateRef_12_5:any;
  _NgFor_12_6:import3.NgFor;
  _text_13: any;
  _text_14: any;
  _el_15: any;
  _text_16: any;
  _el_17: any;
  _text_18: any;
  _el_19: any;
  _text_20: any;
  _text_21: any;
  _el_22: any;
  _text_23: any;
  _el_24: any;
  _text_25: any;
  _el_26: any;
  _text_27: any;
  _text_28: any;
  _el_29: any;
  _text_30: any;
  _text_31: any;
  _el_32: any;
  _text_33: any;
  _text_34: any;
  _el_35: any;
  _text_36: any;
  _text_37: any;
  _el_38: any;
  _text_39: any;
  _text_40: any;
  _el_41: any;
  _text_42: any;
  _text_43: any;
  _text_44: any;
  _text_45: any;
  _el_46: any;
  _text_47: any;
  _el_48: any;
  _text_49: any;
  _text_50: any;
  _el_51: any;
  _text_52: any;
  _text_53: any;
  _text_54: any;
  _text_55: any;
  _text_56: any;
  private _expr_2: any;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import7.AppElement) {
    super(_View_WeatherApp0,renderType_WeatherApp,import10.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import11.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_WeatherApp0);
  }
  createInternal(rootSelector:string):import7.AppElement {
    const parentRenderNode = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'header',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','header');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,23));
    this._el_2 = this.renderer.createElement(this._el_0,'h1',this.debug(2,1,2));
    this.renderer.setElementAttribute(this._el_2,'class','header__title');
    this._text_3 = this.renderer.createText(this._el_2,'Weather PWA',this.debug(3,1,28));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',this.debug(4,1,44));
    this._el_5 = this.renderer.createElement(this._el_0,'button',this.debug(5,2,2));
    this.renderer.setElementAttribute(this._el_5,'aria-label','Refresh');
    this.renderer.setElementAttribute(this._el_5,'class','headerButton');
    this.renderer.setElementAttribute(this._el_5,'id','butRefresh');
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',this.debug(6,2,97));
    this._el_7 = this.renderer.createElement(this._el_0,'button',this.debug(7,3,2));
    this.renderer.setElementAttribute(this._el_7,'aria-label','Add');
    this.renderer.setElementAttribute(this._el_7,'class','headerButton');
    this.renderer.setElementAttribute(this._el_7,'id','butAdd');
    this._text_8 = this.renderer.createText(this._el_0,'\n',this.debug(8,3,85));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(9,4,9));
    this._el_10 = this.renderer.createElement(parentRenderNode,'main',this.debug(10,6,0));
    this.renderer.setElementAttribute(this._el_10,'class','main');
    this._text_11 = this.renderer.createText(this._el_10,'\n  ',this.debug(11,6,19));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,this.debug(12,7,2));
    this._appEl_12 = new import7.AppElement(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import2.TemplateRef_(this._appEl_12,viewFactory_WeatherApp1);
    this._NgFor_12_6 = new import3.NgFor(this._appEl_12.vcRef,this._TemplateRef_12_5,this.parentInjector.get(import12.IterableDiffers),this.ref);
    this._text_13 = this.renderer.createText(this._el_10,'\n',this.debug(13,7,59));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(14,8,7));
    this._el_15 = this.renderer.createElement(parentRenderNode,'div',this.debug(15,10,0));
    this.renderer.setElementAttribute(this._el_15,'class','dialog-container');
    this._text_16 = this.renderer.createText(this._el_15,'\n  ',this.debug(16,10,30));
    this._el_17 = this.renderer.createElement(this._el_15,'div',this.debug(17,11,2));
    this.renderer.setElementAttribute(this._el_17,'class','dialog');
    this._text_18 = this.renderer.createText(this._el_17,'\n    ',this.debug(18,11,22));
    this._el_19 = this.renderer.createElement(this._el_17,'div',this.debug(19,12,4));
    this.renderer.setElementAttribute(this._el_19,'class','dialog-title');
    this._text_20 = this.renderer.createText(this._el_19,'Add new city',this.debug(20,12,30));
    this._text_21 = this.renderer.createText(this._el_17,'\n    ',this.debug(21,12,48));
    this._el_22 = this.renderer.createElement(this._el_17,'div',this.debug(22,13,4));
    this.renderer.setElementAttribute(this._el_22,'class','dialog-body');
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',this.debug(23,13,29));
    this._el_24 = this.renderer.createElement(this._el_22,'select',this.debug(24,14,6));
    this.renderer.setElementAttribute(this._el_24,'id','selectCityToAdd');
    this._text_25 = this.renderer.createText(this._el_24,'\n          ',this.debug(25,14,35));
    this._el_26 = this.renderer.createElement(this._el_24,'option',this.debug(26,15,10));
    this.renderer.setElementAttribute(this._el_26,'value','austin');
    this._text_27 = this.renderer.createText(this._el_26,'Austin, TX',this.debug(27,15,33));
    this._text_28 = this.renderer.createText(this._el_24,'\n          ',this.debug(28,15,52));
    this._el_29 = this.renderer.createElement(this._el_24,'option',this.debug(29,16,10));
    this.renderer.setElementAttribute(this._el_29,'value','boston');
    this._text_30 = this.renderer.createText(this._el_29,'Boston, MA',this.debug(30,16,33));
    this._text_31 = this.renderer.createText(this._el_24,'\n          ',this.debug(31,16,52));
    this._el_32 = this.renderer.createElement(this._el_24,'option',this.debug(32,17,10));
    this.renderer.setElementAttribute(this._el_32,'value','chicago');
    this._text_33 = this.renderer.createText(this._el_32,'Chicago, IL',this.debug(33,17,34));
    this._text_34 = this.renderer.createText(this._el_24,'\n          ',this.debug(34,17,54));
    this._el_35 = this.renderer.createElement(this._el_24,'option',this.debug(35,18,10));
    this.renderer.setElementAttribute(this._el_35,'value','portland');
    this._text_36 = this.renderer.createText(this._el_35,'Portland, OR',this.debug(36,18,35));
    this._text_37 = this.renderer.createText(this._el_24,'\n          ',this.debug(37,18,56));
    this._el_38 = this.renderer.createElement(this._el_24,'option',this.debug(38,19,10));
    this.renderer.setElementAttribute(this._el_38,'value','sanfrancisco');
    this._text_39 = this.renderer.createText(this._el_38,'San Francisco, CA',this.debug(39,19,39));
    this._text_40 = this.renderer.createText(this._el_24,'\n          ',this.debug(40,19,65));
    this._el_41 = this.renderer.createElement(this._el_24,'option',this.debug(41,20,10));
    this.renderer.setElementAttribute(this._el_41,'value','seattle');
    this._text_42 = this.renderer.createText(this._el_41,'Seattle, WA',this.debug(42,20,34));
    this._text_43 = this.renderer.createText(this._el_24,'\n        ',this.debug(43,20,54));
    this._text_44 = this.renderer.createText(this._el_22,'\n    ',this.debug(44,21,17));
    this._text_45 = this.renderer.createText(this._el_17,'\n    ',this.debug(45,22,10));
    this._el_46 = this.renderer.createElement(this._el_17,'div',this.debug(46,23,4));
    this.renderer.setElementAttribute(this._el_46,'class','dialog-buttons');
    this._text_47 = this.renderer.createText(this._el_46,'\n      ',this.debug(47,23,32));
    this._el_48 = this.renderer.createElement(this._el_46,'button',this.debug(48,24,6));
    this.renderer.setElementAttribute(this._el_48,'class','button');
    this.renderer.setElementAttribute(this._el_48,'id','butAddCity');
    this._text_49 = this.renderer.createText(this._el_48,'Add',this.debug(49,24,45));
    this._text_50 = this.renderer.createText(this._el_46,'\n      ',this.debug(50,24,57));
    this._el_51 = this.renderer.createElement(this._el_46,'button',this.debug(51,25,6));
    this.renderer.setElementAttribute(this._el_51,'class','button');
    this.renderer.setElementAttribute(this._el_51,'id','butAddCancel');
    this._text_52 = this.renderer.createText(this._el_51,'Cancel',this.debug(52,25,47));
    this._text_53 = this.renderer.createText(this._el_46,'\n    ',this.debug(53,25,62));
    this._text_54 = this.renderer.createText(this._el_17,'\n  ',this.debug(54,26,10));
    this._text_55 = this.renderer.createText(this._el_15,'\n',this.debug(55,27,8));
    this._text_56 = this.renderer.createText(parentRenderNode,'\n\n\n',this.debug(56,28,6));
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_2 = import11.uninitialized;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import2.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import3.NgFor) && (12 === requestNodeIndex))) { return this._NgFor_12_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(12,7,16);
    const currVal_2 = this.context.cities;
    if (import8.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_12_6.ngForOf = currVal_2;
      this.renderer.setBindingDebugInfo(this._anchor_12,'ng-reflect-ng-for-of',((currVal_2 == null)? null: currVal_2.toString()));
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgFor_12_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_5_0($event):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(5,2,10);
    const pd_0:any = ((<any>this.context.refresh()) !== false);
    return (true && pd_0);
  }
  private _handle_click_7_0($event):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(7,3,10);
    const pd_0:any = ((<any>this.context.add()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_WeatherApp0(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import7.AppElement):import5.AppView<import6.WeatherApp> {
  if ((renderType_WeatherApp === null)) { (renderType_WeatherApp = viewUtils.createRenderComponentType('/Users/robwormald/Dev/demos/ng2-pwa-demo/src/app.html',0,import13.ViewEncapsulation.Emulated,styles_WeatherApp)); }
  return new _View_WeatherApp0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_WeatherApp1:import1.StaticNodeDebugInfo[] = [new import1.StaticNodeDebugInfo([import14.WeatherCard],import14.WeatherCard,{})];
class _View_WeatherApp1 extends import5.DebugAppView<any> {
  _el_0: any;
  private _appEl_0:import7.AppElement;
  _WeatherCard_0_4:import14.WeatherCard;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import7.AppElement) {
    super(_View_WeatherApp1,renderType_WeatherApp,import10.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import11.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_WeatherApp1);
  }
  createInternal(rootSelector:string):import7.AppElement {
    this._el_0 = this.renderer.createElement(null,'weather-card',this.debug(0,7,2));
    this._appEl_0 = new import7.AppElement(0,null,this,this._el_0);
    var compView_0 = import15.viewFactory_WeatherCard0(this.viewUtils,this.injector(0),this._appEl_0);
    this._WeatherCard_0_4 = new import14.WeatherCard();
    this._appEl_0.initComponent(this._WeatherCard_0_4,[],compView_0);
    compView_0.create(this._WeatherCard_0_4,[],null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.WeatherCard) && (0 === requestNodeIndex))) { return this._WeatherCard_0_4; }
    return notFoundResult;
  }
}
function viewFactory_WeatherApp1(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import7.AppElement):import5.AppView<any> {
  return new _View_WeatherApp1(viewUtils,parentInjector,declarationEl);
}
const styles_WeatherApp_Host:any[] = [];
const nodeDebugInfos_WeatherApp_Host0:import1.StaticNodeDebugInfo[] = [new import1.StaticNodeDebugInfo([import6.WeatherApp],import6.WeatherApp,{})];
var renderType_WeatherApp_Host:import4.RenderComponentType = null;
class _View_WeatherApp_Host0 extends import5.DebugAppView<any> {
  _el_0: any;
  private _appEl_0:import7.AppElement;
  _WeatherApp_0_4:import6.WeatherApp;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import7.AppElement) {
    super(_View_WeatherApp_Host0,renderType_WeatherApp_Host,import10.ViewType.HOST,viewUtils,parentInjector,declarationEl,import11.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_WeatherApp_Host0);
  }
  createInternal(rootSelector:string):import7.AppElement {
    this._el_0 = this.selectOrCreateHostElement('weather-app',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import7.AppElement(0,null,this,this._el_0);
    var compView_0 = viewFactory_WeatherApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._WeatherApp_0_4 = new import6.WeatherApp();
    this._appEl_0.initComponent(this._WeatherApp_0_4,[],compView_0);
    compView_0.create(this._WeatherApp_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.WeatherApp) && (0 === requestNodeIndex))) { return this._WeatherApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_WeatherApp_Host0(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import7.AppElement):import5.AppView<any> {
  if ((renderType_WeatherApp_Host === null)) { (renderType_WeatherApp_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.Emulated,styles_WeatherApp_Host)); }
  return new _View_WeatherApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const WeatherAppNgFactory:import16.ComponentFactory<import6.WeatherApp> = new import16.ComponentFactory<import6.WeatherApp>('weather-app',viewFactory_WeatherApp_Host0,import6.WeatherApp);