/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './city-picker.css.shim';
import * as import1 from '@angular/core/src/linker/debug_context';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from './city-picker';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/element';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
const styles_CityPicker:any[] = [import0.styles];
const nodeDebugInfos_CityPicker0:import1.StaticNodeDebugInfo[] = [
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{'picker': null}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{})
]
;
var renderType_CityPicker:import2.RenderComponentType = null;
class _View_CityPicker0 extends import3.DebugAppView<import4.CityPicker> {
  _el_0: any;
  _text_1: any;
  _el_2: any;
  _text_3: any;
  _text_4: any;
  _el_5: any;
  _text_6: any;
  _el_7: any;
  _text_8: any;
  _el_9: any;
  _text_10: any;
  _text_11: any;
  _el_12: any;
  _text_13: any;
  _text_14: any;
  _el_15: any;
  _text_16: any;
  _text_17: any;
  _el_18: any;
  _text_19: any;
  _text_20: any;
  _el_21: any;
  _text_22: any;
  _text_23: any;
  _el_24: any;
  _text_25: any;
  _text_26: any;
  _text_27: any;
  _text_28: any;
  _el_29: any;
  _text_30: any;
  _el_31: any;
  _text_32: any;
  _text_33: any;
  _el_34: any;
  _text_35: any;
  _text_36: any;
  _text_37: any;
  _text_38: any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement) {
    super(_View_CityPicker0,renderType_CityPicker,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_CityPicker0);
  }
  createInternal(rootSelector:string):import7.AppElement {
    const parentRenderNode = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','dialog');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,20));
    this._el_2 = this.renderer.createElement(this._el_0,'div',this.debug(2,1,2));
    this.renderer.setElementAttribute(this._el_2,'class','dialog-title');
    this._text_3 = this.renderer.createText(this._el_2,'Add new city',this.debug(3,1,28));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',this.debug(4,1,46));
    this._el_5 = this.renderer.createElement(this._el_0,'div',this.debug(5,2,2));
    this.renderer.setElementAttribute(this._el_5,'class','dialog-body');
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',this.debug(6,2,27));
    this._el_7 = this.renderer.createElement(this._el_5,'select',this.debug(7,3,4));
    this.renderer.setElementAttribute(this._el_7,'id','selectCityToAdd');
    this._text_8 = this.renderer.createText(this._el_7,'\n          ',this.debug(8,3,41));
    this._el_9 = this.renderer.createElement(this._el_7,'option',this.debug(9,4,10));
    this.renderer.setElementAttribute(this._el_9,'value','austin');
    this._text_10 = this.renderer.createText(this._el_9,'Austin, TX',this.debug(10,4,33));
    this._text_11 = this.renderer.createText(this._el_7,'\n          ',this.debug(11,4,52));
    this._el_12 = this.renderer.createElement(this._el_7,'option',this.debug(12,5,10));
    this.renderer.setElementAttribute(this._el_12,'value','boston');
    this._text_13 = this.renderer.createText(this._el_12,'Boston, MA',this.debug(13,5,33));
    this._text_14 = this.renderer.createText(this._el_7,'\n          ',this.debug(14,5,52));
    this._el_15 = this.renderer.createElement(this._el_7,'option',this.debug(15,6,10));
    this.renderer.setElementAttribute(this._el_15,'value','chicago');
    this._text_16 = this.renderer.createText(this._el_15,'Chicago, IL',this.debug(16,6,34));
    this._text_17 = this.renderer.createText(this._el_7,'\n          ',this.debug(17,6,54));
    this._el_18 = this.renderer.createElement(this._el_7,'option',this.debug(18,7,10));
    this.renderer.setElementAttribute(this._el_18,'value','portland');
    this._text_19 = this.renderer.createText(this._el_18,'Portland, OR',this.debug(19,7,35));
    this._text_20 = this.renderer.createText(this._el_7,'\n          ',this.debug(20,7,56));
    this._el_21 = this.renderer.createElement(this._el_7,'option',this.debug(21,8,10));
    this.renderer.setElementAttribute(this._el_21,'value','sanfrancisco');
    this._text_22 = this.renderer.createText(this._el_21,'San Francisco, CA',this.debug(22,8,39));
    this._text_23 = this.renderer.createText(this._el_7,'\n          ',this.debug(23,8,65));
    this._el_24 = this.renderer.createElement(this._el_7,'option',this.debug(24,9,10));
    this.renderer.setElementAttribute(this._el_24,'value','seattle');
    this._text_25 = this.renderer.createText(this._el_24,'Seattle, WA',this.debug(25,9,34));
    this._text_26 = this.renderer.createText(this._el_7,'\n    ',this.debug(26,9,54));
    this._text_27 = this.renderer.createText(this._el_5,'\n  ',this.debug(27,10,13));
    this._text_28 = this.renderer.createText(this._el_0,'\n  ',this.debug(28,11,8));
    this._el_29 = this.renderer.createElement(this._el_0,'div',this.debug(29,12,2));
    this.renderer.setElementAttribute(this._el_29,'class','dialog-buttons');
    this._text_30 = this.renderer.createText(this._el_29,'\n    ',this.debug(30,12,30));
    this._el_31 = this.renderer.createElement(this._el_29,'button',this.debug(31,13,4));
    this.renderer.setElementAttribute(this._el_31,'class','button');
    this.renderer.setElementAttribute(this._el_31,'id','butAddCity');
    this._text_32 = this.renderer.createText(this._el_31,'Add',this.debug(32,13,77));
    this._text_33 = this.renderer.createText(this._el_29,'\n    ',this.debug(33,13,89));
    this._el_34 = this.renderer.createElement(this._el_29,'button',this.debug(34,14,4));
    this.renderer.setElementAttribute(this._el_34,'class','button');
    this.renderer.setElementAttribute(this._el_34,'id','butAddCancel');
    this._text_35 = this.renderer.createText(this._el_34,'Cancel',this.debug(35,14,75));
    this._text_36 = this.renderer.createText(this._el_29,'\n  ',this.debug(36,14,90));
    this._text_37 = this.renderer.createText(this._el_0,'\n',this.debug(37,15,8));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n',this.debug(38,16,6));
    var disposable_0:Function = this.renderer.listen(this._el_31,'click',this.eventHandler(this._handle_click_31_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return null;
  }
  private _handle_click_31_0($event):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(31,13,43);
    const pd_0:any = ((<any>this.context.save.emit(this._el_7.value)) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(34,14,45);
    const pd_0:any = ((<any>this.context.cancel.emit($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CityPicker0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement):import3.AppView<import4.CityPicker> {
  if ((renderType_CityPicker === null)) { (renderType_CityPicker = viewUtils.createRenderComponentType('/Users/robwormald/Dev/demos/ng2-pwa-demo/src/city-picker.html',0,import10.ViewEncapsulation.Emulated,styles_CityPicker)); }
  return new _View_CityPicker0(viewUtils,parentInjector,declarationEl);
}
const styles_CityPicker_Host:any[] = [];
const nodeDebugInfos_CityPicker_Host0:import1.StaticNodeDebugInfo[] = [new import1.StaticNodeDebugInfo([import4.CityPicker],import4.CityPicker,{})];
var renderType_CityPicker_Host:import2.RenderComponentType = null;
class _View_CityPicker_Host0 extends import3.DebugAppView<any> {
  _el_0: any;
  private _appEl_0:import7.AppElement;
  _CityPicker_0_4:import4.CityPicker;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement) {
    super(_View_CityPicker_Host0,renderType_CityPicker_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_CityPicker_Host0);
  }
  createInternal(rootSelector:string):import7.AppElement {
    this._el_0 = this.selectOrCreateHostElement('city-picker',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import7.AppElement(0,null,this,this._el_0);
    var compView_0 = viewFactory_CityPicker0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CityPicker_0_4 = new import4.CityPicker();
    this._appEl_0.initComponent(this._CityPicker_0_4,[],compView_0);
    compView_0.create(this._CityPicker_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.CityPicker) && (0 === requestNodeIndex))) { return this._CityPicker_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CityPicker_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement):import3.AppView<any> {
  if ((renderType_CityPicker_Host === null)) { (renderType_CityPicker_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_CityPicker_Host)); }
  return new _View_CityPicker_Host0(viewUtils,parentInjector,declarationEl);
}
export const CityPickerNgFactory:import11.ComponentFactory<import4.CityPicker> = new import11.ComponentFactory<import4.CityPicker>('city-picker',viewFactory_CityPicker_Host0,import4.CityPicker);