/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './weather-card.css.shim';
import * as import1 from '@angular/core/src/linker/debug_context';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from './weather-card';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/element';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
const styles_WeatherCard:any[] = [import0.styles];
const nodeDebugInfos_WeatherCard0:import1.StaticNodeDebugInfo[] = [
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{}),
  new import1.StaticNodeDebugInfo([],null,{})
]
;
var renderType_WeatherCard:import2.RenderComponentType = null;
class _View_WeatherCard0 extends import3.DebugAppView<import4.WeatherCard> {
  _el_0: any;
  _text_1: any;
  _el_2: any;
  _text_3: any;
  _el_4: any;
  _text_5: any;
  _el_6: any;
  _text_7: any;
  _el_8: any;
  _text_9: any;
  _el_10: any;
  _text_11: any;
  _el_12: any;
  _text_13: any;
  _el_14: any;
  _text_15: any;
  _el_16: any;
  _text_17: any;
  _el_18: any;
  _el_19: any;
  _text_20: any;
  _text_21: any;
  _text_22: any;
  _text_23: any;
  _el_24: any;
  _text_25: any;
  _el_26: any;
  _text_27: any;
  _el_28: any;
  _el_29: any;
  _text_30: any;
  _text_31: any;
  _text_32: any;
  _el_33: any;
  _text_34: any;
  _el_35: any;
  _text_36: any;
  _el_37: any;
  _text_38: any;
  _el_39: any;
  _text_40: any;
  _el_41: any;
  _text_42: any;
  _text_43: any;
  _el_44: any;
  _text_45: any;
  _text_46: any;
  _text_47: any;
  _text_48: any;
  _el_49: any;
  _text_50: any;
  _el_51: any;
  _text_52: any;
  _el_53: any;
  _text_54: any;
  _el_55: any;
  _text_56: any;
  _el_57: any;
  _text_58: any;
  _el_59: any;
  _text_60: any;
  _text_61: any;
  _el_62: any;
  _text_63: any;
  _el_64: any;
  _text_65: any;
  _text_66: any;
  _text_67: any;
  _el_68: any;
  _text_69: any;
  _el_70: any;
  _text_71: any;
  _el_72: any;
  _text_73: any;
  _el_74: any;
  _text_75: any;
  _el_76: any;
  _text_77: any;
  _text_78: any;
  _el_79: any;
  _text_80: any;
  _el_81: any;
  _text_82: any;
  _text_83: any;
  _text_84: any;
  _el_85: any;
  _text_86: any;
  _el_87: any;
  _text_88: any;
  _el_89: any;
  _text_90: any;
  _el_91: any;
  _text_92: any;
  _el_93: any;
  _text_94: any;
  _text_95: any;
  _el_96: any;
  _text_97: any;
  _el_98: any;
  _text_99: any;
  _text_100: any;
  _text_101: any;
  _el_102: any;
  _text_103: any;
  _el_104: any;
  _text_105: any;
  _el_106: any;
  _text_107: any;
  _el_108: any;
  _text_109: any;
  _el_110: any;
  _text_111: any;
  _text_112: any;
  _el_113: any;
  _text_114: any;
  _el_115: any;
  _text_116: any;
  _text_117: any;
  _text_118: any;
  _el_119: any;
  _text_120: any;
  _el_121: any;
  _text_122: any;
  _el_123: any;
  _text_124: any;
  _el_125: any;
  _text_126: any;
  _el_127: any;
  _text_128: any;
  _text_129: any;
  _el_130: any;
  _text_131: any;
  _el_132: any;
  _text_133: any;
  _text_134: any;
  _text_135: any;
  _el_136: any;
  _text_137: any;
  _el_138: any;
  _text_139: any;
  _el_140: any;
  _text_141: any;
  _el_142: any;
  _text_143: any;
  _el_144: any;
  _text_145: any;
  _text_146: any;
  _el_147: any;
  _text_148: any;
  _el_149: any;
  _text_150: any;
  _text_151: any;
  _text_152: any;
  _el_153: any;
  _text_154: any;
  _el_155: any;
  _text_156: any;
  _el_157: any;
  _text_158: any;
  _el_159: any;
  _text_160: any;
  _el_161: any;
  _text_162: any;
  _text_163: any;
  _el_164: any;
  _text_165: any;
  _el_166: any;
  _text_167: any;
  _text_168: any;
  _text_169: any;
  _text_170: any;
  _text_171: any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement) {
    super(_View_WeatherCard0,renderType_WeatherCard,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_WeatherCard0);
  }
  createInternal(rootSelector:string):import7.AppElement {
    const parentRenderNode = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','card cardTemplate weather-forecast');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',this.debug(1,0,48));
    this._el_2 = this.renderer.createElement(this._el_0,'div',this.debug(2,1,4));
    this.renderer.setElementAttribute(this._el_2,'class','city-key');
    this.renderer.setElementAttribute(this._el_2,'hidden','');
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',this.debug(3,1,39));
    this._el_4 = this.renderer.createElement(this._el_0,'div',this.debug(4,2,4));
    this.renderer.setElementAttribute(this._el_4,'class','location');
    this._text_5 = this.renderer.createText(this._el_0,'\n    ',this.debug(5,2,32));
    this._el_6 = this.renderer.createElement(this._el_0,'div',this.debug(6,3,4));
    this.renderer.setElementAttribute(this._el_6,'class','date');
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',this.debug(7,3,28));
    this._el_8 = this.renderer.createElement(this._el_0,'div',this.debug(8,4,4));
    this.renderer.setElementAttribute(this._el_8,'class','description');
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',this.debug(9,4,35));
    this._el_10 = this.renderer.createElement(this._el_0,'div',this.debug(10,5,4));
    this.renderer.setElementAttribute(this._el_10,'class','current');
    this._text_11 = this.renderer.createText(this._el_10,'\n      ',this.debug(11,5,25));
    this._el_12 = this.renderer.createElement(this._el_10,'div',this.debug(12,6,6));
    this.renderer.setElementAttribute(this._el_12,'class','visual');
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',this.debug(13,6,26));
    this._el_14 = this.renderer.createElement(this._el_12,'div',this.debug(14,7,8));
    this.renderer.setElementAttribute(this._el_14,'class','icon');
    this._text_15 = this.renderer.createText(this._el_12,'\n        ',this.debug(15,7,32));
    this._el_16 = this.renderer.createElement(this._el_12,'div',this.debug(16,8,8));
    this.renderer.setElementAttribute(this._el_16,'class','temperature');
    this._text_17 = this.renderer.createText(this._el_16,'\n          ',this.debug(17,8,33));
    this._el_18 = this.renderer.createElement(this._el_16,'span',this.debug(18,9,10));
    this.renderer.setElementAttribute(this._el_18,'class','value');
    this._el_19 = this.renderer.createElement(this._el_16,'span',this.debug(19,9,37));
    this.renderer.setElementAttribute(this._el_19,'class','scale');
    this._text_20 = this.renderer.createText(this._el_19,'°F',this.debug(20,9,57));
    this._text_21 = this.renderer.createText(this._el_16,'\n        ',this.debug(21,9,66));
    this._text_22 = this.renderer.createText(this._el_12,'\n      ',this.debug(22,10,14));
    this._text_23 = this.renderer.createText(this._el_10,'\n      ',this.debug(23,11,12));
    this._el_24 = this.renderer.createElement(this._el_10,'div',this.debug(24,12,6));
    this.renderer.setElementAttribute(this._el_24,'class','description');
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',this.debug(25,12,31));
    this._el_26 = this.renderer.createElement(this._el_24,'div',this.debug(26,13,8));
    this.renderer.setElementAttribute(this._el_26,'class','feels-like');
    this._text_27 = this.renderer.createText(this._el_26,'\n          ',this.debug(27,13,32));
    this._el_28 = this.renderer.createElement(this._el_26,'span',this.debug(28,14,10));
    this.renderer.setElementAttribute(this._el_28,'class','value');
    this._el_29 = this.renderer.createElement(this._el_26,'span',this.debug(29,14,37));
    this.renderer.setElementAttribute(this._el_29,'class','scale');
    this._text_30 = this.renderer.createText(this._el_29,'°F',this.debug(30,14,57));
    this._text_31 = this.renderer.createText(this._el_26,'\n        ',this.debug(31,14,66));
    this._text_32 = this.renderer.createText(this._el_24,'\n        ',this.debug(32,15,14));
    this._el_33 = this.renderer.createElement(this._el_24,'div',this.debug(33,16,8));
    this.renderer.setElementAttribute(this._el_33,'class','precip');
    this._text_34 = this.renderer.createText(this._el_24,'\n        ',this.debug(34,16,34));
    this._el_35 = this.renderer.createElement(this._el_24,'div',this.debug(35,17,8));
    this.renderer.setElementAttribute(this._el_35,'class','humidity');
    this._text_36 = this.renderer.createText(this._el_24,'\n        ',this.debug(36,17,36));
    this._el_37 = this.renderer.createElement(this._el_24,'div',this.debug(37,18,8));
    this.renderer.setElementAttribute(this._el_37,'class','wind');
    this._text_38 = this.renderer.createText(this._el_37,'\n          ',this.debug(38,18,26));
    this._el_39 = this.renderer.createElement(this._el_37,'span',this.debug(39,19,10));
    this.renderer.setElementAttribute(this._el_39,'class','value');
    this._text_40 = this.renderer.createText(this._el_37,'\n          ',this.debug(40,19,37));
    this._el_41 = this.renderer.createElement(this._el_37,'span',this.debug(41,20,10));
    this.renderer.setElementAttribute(this._el_41,'class','scale');
    this._text_42 = this.renderer.createText(this._el_41,'mph',this.debug(42,20,30));
    this._text_43 = this.renderer.createText(this._el_37,'\n          ',this.debug(43,20,40));
    this._el_44 = this.renderer.createElement(this._el_37,'span',this.debug(44,21,10));
    this.renderer.setElementAttribute(this._el_44,'class','direction');
    this._text_45 = this.renderer.createText(this._el_37,'°\n        ',this.debug(45,21,41));
    this._text_46 = this.renderer.createText(this._el_24,'\n      ',this.debug(46,22,14));
    this._text_47 = this.renderer.createText(this._el_10,'\n    ',this.debug(47,23,12));
    this._text_48 = this.renderer.createText(this._el_0,'\n    ',this.debug(48,24,10));
    this._el_49 = this.renderer.createElement(this._el_0,'div',this.debug(49,25,4));
    this.renderer.setElementAttribute(this._el_49,'class','future');
    this._text_50 = this.renderer.createText(this._el_49,'\n      ',this.debug(50,25,24));
    this._el_51 = this.renderer.createElement(this._el_49,'div',this.debug(51,26,6));
    this.renderer.setElementAttribute(this._el_51,'class','oneday');
    this._text_52 = this.renderer.createText(this._el_51,'\n        ',this.debug(52,26,26));
    this._el_53 = this.renderer.createElement(this._el_51,'div',this.debug(53,27,8));
    this.renderer.setElementAttribute(this._el_53,'class','date');
    this._text_54 = this.renderer.createText(this._el_51,'\n        ',this.debug(54,27,32));
    this._el_55 = this.renderer.createElement(this._el_51,'div',this.debug(55,28,8));
    this.renderer.setElementAttribute(this._el_55,'class','icon');
    this._text_56 = this.renderer.createText(this._el_51,'\n        ',this.debug(56,28,32));
    this._el_57 = this.renderer.createElement(this._el_51,'div',this.debug(57,29,8));
    this.renderer.setElementAttribute(this._el_57,'class','temp-high');
    this._text_58 = this.renderer.createText(this._el_57,'\n          ',this.debug(58,29,31));
    this._el_59 = this.renderer.createElement(this._el_57,'span',this.debug(59,30,10));
    this.renderer.setElementAttribute(this._el_59,'class','value');
    this._text_60 = this.renderer.createText(this._el_57,'°\n        ',this.debug(60,30,37));
    this._text_61 = this.renderer.createText(this._el_51,'\n        ',this.debug(61,31,14));
    this._el_62 = this.renderer.createElement(this._el_51,'div',this.debug(62,32,8));
    this.renderer.setElementAttribute(this._el_62,'class','temp-low');
    this._text_63 = this.renderer.createText(this._el_62,'\n          ',this.debug(63,32,30));
    this._el_64 = this.renderer.createElement(this._el_62,'span',this.debug(64,33,10));
    this.renderer.setElementAttribute(this._el_64,'class','value');
    this._text_65 = this.renderer.createText(this._el_62,'°\n        ',this.debug(65,33,37));
    this._text_66 = this.renderer.createText(this._el_51,'\n      ',this.debug(66,34,14));
    this._text_67 = this.renderer.createText(this._el_49,'\n      ',this.debug(67,35,12));
    this._el_68 = this.renderer.createElement(this._el_49,'div',this.debug(68,36,6));
    this.renderer.setElementAttribute(this._el_68,'class','oneday');
    this._text_69 = this.renderer.createText(this._el_68,'\n        ',this.debug(69,36,26));
    this._el_70 = this.renderer.createElement(this._el_68,'div',this.debug(70,37,8));
    this.renderer.setElementAttribute(this._el_70,'class','date');
    this._text_71 = this.renderer.createText(this._el_68,'\n        ',this.debug(71,37,32));
    this._el_72 = this.renderer.createElement(this._el_68,'div',this.debug(72,38,8));
    this.renderer.setElementAttribute(this._el_72,'class','icon');
    this._text_73 = this.renderer.createText(this._el_68,'\n        ',this.debug(73,38,32));
    this._el_74 = this.renderer.createElement(this._el_68,'div',this.debug(74,39,8));
    this.renderer.setElementAttribute(this._el_74,'class','temp-high');
    this._text_75 = this.renderer.createText(this._el_74,'\n          ',this.debug(75,39,31));
    this._el_76 = this.renderer.createElement(this._el_74,'span',this.debug(76,40,10));
    this.renderer.setElementAttribute(this._el_76,'class','value');
    this._text_77 = this.renderer.createText(this._el_74,'°\n        ',this.debug(77,40,37));
    this._text_78 = this.renderer.createText(this._el_68,'\n        ',this.debug(78,41,14));
    this._el_79 = this.renderer.createElement(this._el_68,'div',this.debug(79,42,8));
    this.renderer.setElementAttribute(this._el_79,'class','temp-low');
    this._text_80 = this.renderer.createText(this._el_79,'\n          ',this.debug(80,42,30));
    this._el_81 = this.renderer.createElement(this._el_79,'span',this.debug(81,43,10));
    this.renderer.setElementAttribute(this._el_81,'class','value');
    this._text_82 = this.renderer.createText(this._el_79,'°\n        ',this.debug(82,43,37));
    this._text_83 = this.renderer.createText(this._el_68,'\n      ',this.debug(83,44,14));
    this._text_84 = this.renderer.createText(this._el_49,'\n      ',this.debug(84,45,12));
    this._el_85 = this.renderer.createElement(this._el_49,'div',this.debug(85,46,6));
    this.renderer.setElementAttribute(this._el_85,'class','oneday');
    this._text_86 = this.renderer.createText(this._el_85,'\n        ',this.debug(86,46,26));
    this._el_87 = this.renderer.createElement(this._el_85,'div',this.debug(87,47,8));
    this.renderer.setElementAttribute(this._el_87,'class','date');
    this._text_88 = this.renderer.createText(this._el_85,'\n        ',this.debug(88,47,32));
    this._el_89 = this.renderer.createElement(this._el_85,'div',this.debug(89,48,8));
    this.renderer.setElementAttribute(this._el_89,'class','icon');
    this._text_90 = this.renderer.createText(this._el_85,'\n        ',this.debug(90,48,32));
    this._el_91 = this.renderer.createElement(this._el_85,'div',this.debug(91,49,8));
    this.renderer.setElementAttribute(this._el_91,'class','temp-high');
    this._text_92 = this.renderer.createText(this._el_91,'\n          ',this.debug(92,49,31));
    this._el_93 = this.renderer.createElement(this._el_91,'span',this.debug(93,50,10));
    this.renderer.setElementAttribute(this._el_93,'class','value');
    this._text_94 = this.renderer.createText(this._el_91,'°\n        ',this.debug(94,50,37));
    this._text_95 = this.renderer.createText(this._el_85,'\n        ',this.debug(95,51,14));
    this._el_96 = this.renderer.createElement(this._el_85,'div',this.debug(96,52,8));
    this.renderer.setElementAttribute(this._el_96,'class','temp-low');
    this._text_97 = this.renderer.createText(this._el_96,'\n          ',this.debug(97,52,30));
    this._el_98 = this.renderer.createElement(this._el_96,'span',this.debug(98,53,10));
    this.renderer.setElementAttribute(this._el_98,'class','value');
    this._text_99 = this.renderer.createText(this._el_96,'°\n        ',this.debug(99,53,37));
    this._text_100 = this.renderer.createText(this._el_85,'\n      ',this.debug(100,54,14));
    this._text_101 = this.renderer.createText(this._el_49,'\n      ',this.debug(101,55,12));
    this._el_102 = this.renderer.createElement(this._el_49,'div',this.debug(102,56,6));
    this.renderer.setElementAttribute(this._el_102,'class','oneday');
    this._text_103 = this.renderer.createText(this._el_102,'\n        ',this.debug(103,56,26));
    this._el_104 = this.renderer.createElement(this._el_102,'div',this.debug(104,57,8));
    this.renderer.setElementAttribute(this._el_104,'class','date');
    this._text_105 = this.renderer.createText(this._el_102,'\n        ',this.debug(105,57,32));
    this._el_106 = this.renderer.createElement(this._el_102,'div',this.debug(106,58,8));
    this.renderer.setElementAttribute(this._el_106,'class','icon');
    this._text_107 = this.renderer.createText(this._el_102,'\n        ',this.debug(107,58,32));
    this._el_108 = this.renderer.createElement(this._el_102,'div',this.debug(108,59,8));
    this.renderer.setElementAttribute(this._el_108,'class','temp-high');
    this._text_109 = this.renderer.createText(this._el_108,'\n          ',this.debug(109,59,31));
    this._el_110 = this.renderer.createElement(this._el_108,'span',this.debug(110,60,10));
    this.renderer.setElementAttribute(this._el_110,'class','value');
    this._text_111 = this.renderer.createText(this._el_108,'°\n        ',this.debug(111,60,37));
    this._text_112 = this.renderer.createText(this._el_102,'\n        ',this.debug(112,61,14));
    this._el_113 = this.renderer.createElement(this._el_102,'div',this.debug(113,62,8));
    this.renderer.setElementAttribute(this._el_113,'class','temp-low');
    this._text_114 = this.renderer.createText(this._el_113,'\n          ',this.debug(114,62,30));
    this._el_115 = this.renderer.createElement(this._el_113,'span',this.debug(115,63,10));
    this.renderer.setElementAttribute(this._el_115,'class','value');
    this._text_116 = this.renderer.createText(this._el_113,'°\n        ',this.debug(116,63,37));
    this._text_117 = this.renderer.createText(this._el_102,'\n      ',this.debug(117,64,14));
    this._text_118 = this.renderer.createText(this._el_49,'\n      ',this.debug(118,65,12));
    this._el_119 = this.renderer.createElement(this._el_49,'div',this.debug(119,66,6));
    this.renderer.setElementAttribute(this._el_119,'class','oneday');
    this._text_120 = this.renderer.createText(this._el_119,'\n        ',this.debug(120,66,26));
    this._el_121 = this.renderer.createElement(this._el_119,'div',this.debug(121,67,8));
    this.renderer.setElementAttribute(this._el_121,'class','date');
    this._text_122 = this.renderer.createText(this._el_119,'\n        ',this.debug(122,67,32));
    this._el_123 = this.renderer.createElement(this._el_119,'div',this.debug(123,68,8));
    this.renderer.setElementAttribute(this._el_123,'class','icon');
    this._text_124 = this.renderer.createText(this._el_119,'\n        ',this.debug(124,68,32));
    this._el_125 = this.renderer.createElement(this._el_119,'div',this.debug(125,69,8));
    this.renderer.setElementAttribute(this._el_125,'class','temp-high');
    this._text_126 = this.renderer.createText(this._el_125,'\n          ',this.debug(126,69,31));
    this._el_127 = this.renderer.createElement(this._el_125,'span',this.debug(127,70,10));
    this.renderer.setElementAttribute(this._el_127,'class','value');
    this._text_128 = this.renderer.createText(this._el_125,'°\n        ',this.debug(128,70,37));
    this._text_129 = this.renderer.createText(this._el_119,'\n        ',this.debug(129,71,14));
    this._el_130 = this.renderer.createElement(this._el_119,'div',this.debug(130,72,8));
    this.renderer.setElementAttribute(this._el_130,'class','temp-low');
    this._text_131 = this.renderer.createText(this._el_130,'\n          ',this.debug(131,72,30));
    this._el_132 = this.renderer.createElement(this._el_130,'span',this.debug(132,73,10));
    this.renderer.setElementAttribute(this._el_132,'class','value');
    this._text_133 = this.renderer.createText(this._el_130,'°\n        ',this.debug(133,73,37));
    this._text_134 = this.renderer.createText(this._el_119,'\n      ',this.debug(134,74,14));
    this._text_135 = this.renderer.createText(this._el_49,'\n      ',this.debug(135,75,12));
    this._el_136 = this.renderer.createElement(this._el_49,'div',this.debug(136,76,6));
    this.renderer.setElementAttribute(this._el_136,'class','oneday');
    this._text_137 = this.renderer.createText(this._el_136,'\n        ',this.debug(137,76,26));
    this._el_138 = this.renderer.createElement(this._el_136,'div',this.debug(138,77,8));
    this.renderer.setElementAttribute(this._el_138,'class','date');
    this._text_139 = this.renderer.createText(this._el_136,'\n        ',this.debug(139,77,32));
    this._el_140 = this.renderer.createElement(this._el_136,'div',this.debug(140,78,8));
    this.renderer.setElementAttribute(this._el_140,'class','icon');
    this._text_141 = this.renderer.createText(this._el_136,'\n        ',this.debug(141,78,32));
    this._el_142 = this.renderer.createElement(this._el_136,'div',this.debug(142,79,8));
    this.renderer.setElementAttribute(this._el_142,'class','temp-high');
    this._text_143 = this.renderer.createText(this._el_142,'\n          ',this.debug(143,79,31));
    this._el_144 = this.renderer.createElement(this._el_142,'span',this.debug(144,80,10));
    this.renderer.setElementAttribute(this._el_144,'class','value');
    this._text_145 = this.renderer.createText(this._el_142,'°\n        ',this.debug(145,80,37));
    this._text_146 = this.renderer.createText(this._el_136,'\n        ',this.debug(146,81,14));
    this._el_147 = this.renderer.createElement(this._el_136,'div',this.debug(147,82,8));
    this.renderer.setElementAttribute(this._el_147,'class','temp-low');
    this._text_148 = this.renderer.createText(this._el_147,'\n          ',this.debug(148,82,30));
    this._el_149 = this.renderer.createElement(this._el_147,'span',this.debug(149,83,10));
    this.renderer.setElementAttribute(this._el_149,'class','value');
    this._text_150 = this.renderer.createText(this._el_147,'°\n        ',this.debug(150,83,37));
    this._text_151 = this.renderer.createText(this._el_136,'\n      ',this.debug(151,84,14));
    this._text_152 = this.renderer.createText(this._el_49,'\n      ',this.debug(152,85,12));
    this._el_153 = this.renderer.createElement(this._el_49,'div',this.debug(153,86,6));
    this.renderer.setElementAttribute(this._el_153,'class','oneday');
    this._text_154 = this.renderer.createText(this._el_153,'\n        ',this.debug(154,86,26));
    this._el_155 = this.renderer.createElement(this._el_153,'div',this.debug(155,87,8));
    this.renderer.setElementAttribute(this._el_155,'class','date');
    this._text_156 = this.renderer.createText(this._el_153,'\n        ',this.debug(156,87,32));
    this._el_157 = this.renderer.createElement(this._el_153,'div',this.debug(157,88,8));
    this.renderer.setElementAttribute(this._el_157,'class','icon');
    this._text_158 = this.renderer.createText(this._el_153,'\n        ',this.debug(158,88,32));
    this._el_159 = this.renderer.createElement(this._el_153,'div',this.debug(159,89,8));
    this.renderer.setElementAttribute(this._el_159,'class','temp-high');
    this._text_160 = this.renderer.createText(this._el_159,'\n          ',this.debug(160,89,31));
    this._el_161 = this.renderer.createElement(this._el_159,'span',this.debug(161,90,10));
    this.renderer.setElementAttribute(this._el_161,'class','value');
    this._text_162 = this.renderer.createText(this._el_159,'°\n        ',this.debug(162,90,37));
    this._text_163 = this.renderer.createText(this._el_153,'\n        ',this.debug(163,91,14));
    this._el_164 = this.renderer.createElement(this._el_153,'div',this.debug(164,92,8));
    this.renderer.setElementAttribute(this._el_164,'class','temp-low');
    this._text_165 = this.renderer.createText(this._el_164,'\n          ',this.debug(165,92,30));
    this._el_166 = this.renderer.createElement(this._el_164,'span',this.debug(166,93,10));
    this.renderer.setElementAttribute(this._el_166,'class','value');
    this._text_167 = this.renderer.createText(this._el_164,'°\n        ',this.debug(167,93,37));
    this._text_168 = this.renderer.createText(this._el_153,'\n      ',this.debug(168,94,14));
    this._text_169 = this.renderer.createText(this._el_49,'\n    ',this.debug(169,95,12));
    this._text_170 = this.renderer.createText(this._el_0,'\n  ',this.debug(170,96,10));
    this._text_171 = this.renderer.createText(parentRenderNode,'\n',this.debug(171,97,8));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._text_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._el_138,
      this._text_139,
      this._el_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._el_159,
      this._text_160,
      this._el_161,
      this._text_162,
      this._text_163,
      this._el_164,
      this._text_165,
      this._el_166,
      this._text_167,
      this._text_168,
      this._text_169,
      this._text_170,
      this._text_171
    ]
    ,[],[]);
    return null;
  }
}
export function viewFactory_WeatherCard0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement):import3.AppView<import4.WeatherCard> {
  if ((renderType_WeatherCard === null)) { (renderType_WeatherCard = viewUtils.createRenderComponentType('/Users/robwormald/Dev/demos/ng2-pwa-demo/src/weather-card.html',0,import10.ViewEncapsulation.Emulated,styles_WeatherCard)); }
  return new _View_WeatherCard0(viewUtils,parentInjector,declarationEl);
}
const styles_WeatherCard_Host:any[] = [];
const nodeDebugInfos_WeatherCard_Host0:import1.StaticNodeDebugInfo[] = [new import1.StaticNodeDebugInfo([import4.WeatherCard],import4.WeatherCard,{})];
var renderType_WeatherCard_Host:import2.RenderComponentType = null;
class _View_WeatherCard_Host0 extends import3.DebugAppView<any> {
  _el_0: any;
  private _appEl_0:import7.AppElement;
  _WeatherCard_0_4:import4.WeatherCard;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement) {
    super(_View_WeatherCard_Host0,renderType_WeatherCard_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectionStrategy.CheckAlways,nodeDebugInfos_WeatherCard_Host0);
  }
  createInternal(rootSelector:string):import7.AppElement {
    this._el_0 = this.selectOrCreateHostElement('weather-card',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import7.AppElement(0,null,this,this._el_0);
    var compView_0 = viewFactory_WeatherCard0(this.viewUtils,this.injector(0),this._appEl_0);
    this._WeatherCard_0_4 = new import4.WeatherCard();
    this._appEl_0.initComponent(this._WeatherCard_0_4,[],compView_0);
    compView_0.create(this._WeatherCard_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.WeatherCard) && (0 === requestNodeIndex))) { return this._WeatherCard_0_4; }
    return notFoundResult;
  }
}
function viewFactory_WeatherCard_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import7.AppElement):import3.AppView<any> {
  if ((renderType_WeatherCard_Host === null)) { (renderType_WeatherCard_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_WeatherCard_Host)); }
  return new _View_WeatherCard_Host0(viewUtils,parentInjector,declarationEl);
}
export const WeatherCardNgFactory:import11.ComponentFactory<import4.WeatherCard> = new import11.ComponentFactory<import4.WeatherCard>('weather-card',viewFactory_WeatherCard_Host0,import4.WeatherCard);